# Generated by Django 6.1.1 on 2026-10-03 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KeyValueStore',
            fields=[
                ('k', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('v', models.TextField()),
            ],
            options={
                'db_table': 'kv',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.CharField(default='General', max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('status', models.CharField(default='backlog', max_length=50)),
                ('tags', models.TextField(blank=True, default='')),
                ('notes', models.TextField(blank=True, default='')),
                ('url', models.URLField(blank=True, default='')),
                ('due', models.DateField()),
                ('interval', models.IntegerField(default=0)),
                ('priority', models.IntegerField(default=3)),
                ('done_at', models.DateField(blank=True, null=True)),
                ('spawned', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'tasks',
            },
        ),
    ]
