# Generated by Django 6.1.1 on 2026-10-03 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='room',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
